config/routes.rb
Rails.application.routes.draw do

  #homes
  root 'homes#top'
  get 'homes/about' => "homes#about"

  #devise
  devise_for :publics
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :public do
    #住所
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]

    #カート内商品
    resources :cart_items, only: [:index, :create, :update, :destroy]
    get "cart_items/destroy_all" => "cart_items#destroy_all", as: :destroy_all

    #顧客
    resource :customer, only: [:show, :edit, :update]
    get "customers/unsubscribe" => "customers#unsubscribe", as: :unsubscribe
    delete "customers/withdraw" => "customers#withdraw", as: :withdraw

    #商品
    resources :items, only: [:index, :show]

    #注文
    resources :orders, only: [:new, :create, :index, :show]
    post "orders/comfirm" => "orders#comfirm", as: :comfirm
    get "orders/complete" => "orders#complete", as: :complete

  end

  namespace :admin do
    #顧客情報
    resources :customers, only: [:index, :show, :edit, :destroy, :update]

    #ジャンル
    resources :genres, only: [:index, :create, :edit, :update]

    #商品
    resources :items

    #注文詳細
    resources :order_details, only: [:update]

    #注文
    resources :orders, only: [:index, :show, :update]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :telephone_number, presence: true
  validates :address, presence: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!

  #会員一覧
  def index
    @publics = Public.page(params[:page]).per(10)
  end

  #会員詳細
  def show
     @public = Public.find(params[:id])
  end

  #会員情報編集
  def edit
     @public = Public.find(params[:id])
  end

  #会員大会？←後ほど編集予定
  def destroy
     @public = Public.find(params[:id])
     @public.destroy
  end

  #会員除法更新
  def update
     @public = Public.find(params[:id])
     if @public.update(public_params)
       redirect_to admin_customer_path
     else
       render "edit"
     end
  end

  def public_params
    params.require(:public).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :address, :postal_code, :telephone_number, :is_deleted)
  end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<% if @public.errors.any? %>
  <div id="error_explanation" class="mt-2">
    <ul>
      <% @public.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="mx-auto w-50">
  <div class="row m-3">
    <p class="col-md-3"><%= link_to "戻る", admin_customer_path(@public), class: "fas fa-arrow-circle-left btn btn-lg" %></p>
    <h2 class="text-center col-md-9">登録情報編集</h2>
  </div>

  <%= form_with model: @public, url: admin_customer_path, local: true , method: :patch do |f| %>

    <div class="form-inline mb-3">
    <label class="mr-4">会員ID</label>
    <p><%= @public.id %></p>
    </div>
    <div class="form-inline mb-3">
      <label class="mr-4">お名前　</label>
      <div class="form-group">
        <%= f.text_field :last_name, autofocus: true, placeholder: "姓", class: "form-control mr-3" %>
      </div>
      <div class="form-group">
        <%= f.text_field :first_name, autofocus: true, placeholder: "名", class: "form-control" %>
      </div>
    </div>
    <div class="form-inline mb-3">
      <label class="mr-4">フリガナ</label>
      <div class="form-group mr-3">
        <%= f.text_field :last_name_kana, placeholder: "セイ", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.text_field :first_name_kana, placeholder: "メイ", class: "form-control" %>
      </div>
    </div>
      <div class="form-group">
      <%= f.label "郵便番号" %><br />
      <%= f.text_field :postal_code, autocomplete: 'postcode', class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label "住所" %><br />
      <%= f.text_field :address, autocomplete: 'address', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label "メールアドレス" %><br />
      <%= f.email_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label "電話番号" %><br />
      <%= f.text_field :telephone_number, class: 'form-control' %>
    </div>
    <div class="row mb-3">
    <%= f.label :is_deleted, "会員ステータス", class: "col-md-4"  %>
    <%= f.radio_button :is_deleted, false, class: 'form-control-md mr-1', style: "width: 20px; height: 20px;" %><span class="mr-5">有効</span>
    <%= f.radio_button :is_deleted, true, class: 'form-control-md mr-1', style: "width: 20px; height: 20px;" %><span>退会</span>
    </div>



    <div class="form-group">
      <%= f.submit "変更内容を保存", class: "btn btn-block btn-success" %>

    </div>
  <% end  %>

</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <h2 class="text-center my-3">会員一覧</h2>
  <table class="table table-hover table-bordered table-condensed">
    <thead>
      <tr class="info">
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>

    <tbody>
      <% @publics.each do |public| %>
        <tr>
          <td class="info col-xs-1">
            <%= public.id %>
          </td>
          <td class="text-left">
            <%= link_to admin_customer_path(public), class: "btn-link"  do %>
              <i class="far fa-user"></i>
              <%= public.last_name %><%= public.first_name %>
            <% end %>
          </td>
          <td class="text-left">
            <%= public.email %>
          </td>
          <td class="col-xs-2">
            <% if public.is_deleted %>
              <p>退会済</p>
            <% else %>
              <p>有効</p>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class= "text-center"><%= paginate(@publics) %></div>
</div>

app/views/admin/customers/show.html.erb
<div class="container mt-3">
	<div calss="row">
    <div class="col">
			<i class="far fa-user fa-lg"></i>
			<span class="px-3 mb-2" style="font-size: 24px; background-color: #d3d3d3">
				<%= @public.last_name %><%= @public.first_name %>さんの会員詳細
			</span>
				<table class="table table-borderless mt-4">
					<tbody>
						<tr>
							<td class="info col-xs-2">会員ID</td>
							<td class="text-left"><%= @public.id %></td>
						</tr>
						<tr>
							<td class="info col-xs-2">氏名</td>
							<td class="text-left"><%= @public.last_name %><%= @public.first_name %></td>
						</tr>
						<tr>
							<td class="info">フリガナ</td>
							<td class="text-left"><%= @public.last_name_kana %><%= @public.first_name_kana %></td>
						</tr>
						<tr>
							<td class="info">郵便番号</td>
							<td class="text-left"><%= @public.postal_code %></td>
						</tr>
						<tr>
							<td class="info">住所</td>
							<td class="text-left"><%= @public.address %></td>
						</tr>
						<tr>
							<td class="info">電話番号</td>
							<td class="text-left"><%= @public.telephone_number %></td>
						</tr>
						<tr>
							<td class="info">メールアドレス</td>
							<td class="text-left"><%= @public.email %></td>
						</tr>
						<tr>
							<td class="info">会員ステータス</td>
							<% if @public.is_deleted == false %>
							<td class ="text-success">有効</td>
							<% else %>
							<td class ="text-danger">退会済み</td>
							<% end %>
						</tr>
					</tbody>
				</table>
			<div class="d-flex">
				<div class="mr-5">
				  <%= link_to " 編集する", edit_admin_customer_path(@public),class: "btn btn-success" %>
				</div>
				<div class="colspan">
					<%= link_to "注文履歴一覧を見る", admin_orders_path(@public), class: "mr-2 btn btn-info" %>
				</div>
			</div>
		</div>
	</div>
</div>