config/routes.rb
Rails.application.routes.draw do

  #homes
  root 'homes#top'
  get 'homes/about' => "homes#about"

  #devise
  devise_for :publics
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :public do
    #住所
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]

    #カート内商品
    resources :cart_items, only: [:index, :create, :update, :destroy]
    get "cart_items/destroy_all" => "cart_items#destroy_all", as: :destroy_all

    #顧客
    resource :customer, only: [:show, :edit, :update]
    get "customers/unsubscribe" => "customers#unsubscribe", as: :unsubscribe
    delete "customers/withdraw" => "customers#withdraw", as: :withdraw

    #商品
    resources :items, only: [:index, :show]

    #注文
    resources :orders, only: [:new, :create, :index, :show]
    post "orders/comfirm" => "orders#comfirm", as: :comfirm
    get "orders/complete" => "orders#complete", as: :complete

  end

  namespace :admin do
    #顧客情報
    resources :customers, only: [:index, :show, :edit, :destroy, :update]

    #ジャンル
    resources :genres, only: [:index, :create, :edit, :update]

    #商品
    resources :items

    #注文詳細
    resources :order_details, only: [:update]

    #注文
    resources :orders, only: [:index, :show, :update]
  end
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :public
  has_many :order_items, dependent: :destroy
  has_many :oreder_details, dependent: :destroy
  has_many :items, through: :oreder_details

  #validates :total_payment, presence: true, numericality: { greater_than: 0 }
  validates :shipping_cost, presence: true
  validates :payment_method, presence: true
  validates :status, presence: true
  validates :name, presence: true
  validates :postal_code, presence: true, length: { is: 7 }
  validates :address, presence: true
  validates :public_id, presence: true

  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }

   def self.total_amount_calculator(cart_items)
    sum = 0
    cart_items.each do |cart_item|
      sum += cart_item.amount * cart_item.item.price
    end
    sum * 1.1
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

 before_action :authenticate_admin!

  def index
    @orders = Order.all.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @oreder_details = @order.oreder_details
  end

  def update

    @order = Order.find(params[:id])
    status = Order.statuses[order_params[:status]]

    if @order.update(order_params)

      if status >= Order.statuses["入金確認"]
        @order.oreder_details.each do |oreder_detail|
          oreder_detail.update(making_status: 1)
        end
      else
        @order.oreder_details.each do |oreder_detail|
          oreder_detail.update(making_status: 0)
        end
      end

      redirect_to admin_order_path(@order)
    else
      @oreder_details = @order.oreder_details
      render "show"
    end
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="page_title offset-1 my-3">注文履歴一覧</div>
<table class="table table-bordered">
  <thead class="thead-light">
    <tr>
      <th>注文日</th>
      <th>配送先</th>
      <th>注文商品</th>
      <th>支払金額</th>
      <th>ステータス</th>
      <th>注文詳細</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
    <tr>
      <td class="align-middle"><%= order.created_at.strftime('%Y/%m/%d') %></td>
      <td>
        <%= order.postal_code %><br>
        <%= order.address %><br>
        <%= order.name %>
      </td>
      <td class="align-middle">
        <% order.items.each do |item| %>
          <%= item.name %><br>
        <% end %>
      </td>
      <td class="align-middle"><%= order.total_payment.to_i.to_s(:delimited) %>円</td>
      <td class="align-middle"><%= order.status %></td>
      <td class="align-middle"><%= link_to "表示する", admin_order_path(order), class: "btn btn-sm btn-primary offset-1 col-10" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class ="offset-5"><%= paginate @orders %></div>

app/views/admin/orders/show.html.erb
<div class="col-12">
  <h3 class="my-5"><span class="page_title">注文履歴詳細</span></h3>
  <table class="mb-5 col-6">
    <tbody>
      <tr>
        <th>購入者</th>
        <td>
          <%= link_to admin_customer_path(@order.public) do %>
            <%= @order.public.last_name + @order.public.first_name %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th class="pt-3">注文日</th>
        <td class="pt-3"><%= @order.created_at.strftime('%Y/%m/%d') %></td>
      </tr>
      <tr>
        <th class="pt-3">配送先</th>
        <td class="pt-3">〒<%= @order.postal_code %> <%= @order.address %> <br> <%= @order.name %></td>
      </tr>
      <tr>
        <th class="pt-3">支払い方法</th>
        <td class="pt-3"><%= @order.payment_method %></td>
      </tr>
      <tr>
        <th class="pt-3">注文ステータス</th>
        <td class="pt-3">
          <%= form_with model: @order, url:admin_order_path, method: :patch, local: true do |f| %>
            <div class="d-flex">
              <%= f.select :status, Order.statuses.keys, {}, { class: 'form-control col-5' } %>
              <%= f.submit "更新", class: 'btn btn-success btn-sm ml-4' %>
            </div>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>

  <div class="order-detail pt-5 d-flex">
    <table class="table col-8 mr-5" style="position: relative;">
      <thead class="table-active">
        <tr>
          <th style="width: 25%;">商品名</th>
          <th style="width: 20%;">単価（税込）</th>
          <th style="width: 10%;">数量</th>
          <th style="width: 15%;">小計</th>
          <th style="width: 30%;">制作ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @oreder_details.each do |oreder_detail| %>
          <tr>
            <td><%= oreder_detail.item.name %></td>
            <td><%= oreder_detail.item.price %></td>
            <td><%= oreder_detail.amount %></td>
            <td><%= sub_price(oreder_detail) %>円</td>
            <td>
              <%= form_with model: oreder_detail, url: admin_order_detail_path(oreder_detail), method: :patch do |f| %>
                <%= f.hidden_field :oreder_detail_id, :value => oreder_detail.id %>
                <div class="d-flex">
                  <%= f.select :making_status, OrederDetail.making_statuses.keys, {}, { class: 'form-control col-8' } %>
                  <%= f.submit "更新", class: 'btn btn-success btn-sm ml-3' %>
                </div>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="order-detail-info col-4 mt-5 pl-5" style="position: absolute; bottom: 10px; right: 0;">
      <table class="col-8">
        <tbody>
          <tr>
            <th>商品合計</th>
            <td style="text-align: end;"><%= total_payment(@oreder_details) %>円</td>
          </tr>
          <tr>
            <th>送料</th>
            <td style="text-align: end;">800円</td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <td style="text-align: end;"><%= total_payment(@oreder_details) + 800 %>円</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>