config/routes.rb
Rails.application.routes.draw do

  #homes
  root 'homes#top'
  get 'homes/about' => "homes#about"

  #devise
  devise_for :publics
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :public do
    #住所
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]

    #カート内商品
    resources :cart_items, only: [:index, :create, :update, :destroy]
    get "cart_items/destroy_all" => "cart_items#destroy_all", as: :destroy_all

    #顧客
    resource :customer, only: [:show, :edit, :update]
    get "customers/unsubscribe" => "customers#unsubscribe", as: :unsubscribe
    delete "customers/withdraw" => "customers#withdraw", as: :withdraw

    #商品
    resources :items, only: [:index, :show]

    #注文
    resources :orders, only: [:new, :create, :index, :show]
    post "orders/comfirm" => "orders#comfirm", as: :comfirm
    get "orders/complete" => "orders#complete", as: :complete

  end

  namespace :admin do
    #顧客情報
    resources :customers, only: [:index, :show, :edit, :destroy, :update]

    #ジャンル
    resources :genres, only: [:index, :create, :edit, :update]

    #商品
    resources :items

    #注文詳細
    resources :order_details, only: [:update]

    #注文
    resources :orders, only: [:index, :show, :update]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  #アソシエーション
  belongs_to :public

  validates :public_id, presence: true
  validates :name, presence: true
  validates :postal_code, presence: true, length: { is: 7 }
  validates :address, presence: true

 #登録済み住所
  def params_registred_address
    "〒" + self.postal_code + "  " + self.address + "  " +self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :public
  belongs_to :item

  validates :item_id, presence: true
  validates :amount, presence: true, length: { minimum: 1 }
  validates :public_id, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :telephone_number, presence: true
  validates :address, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :publics, through: :cart_items
  has_many :cart_items
  has_many :oreder_details
  has_many :orders, through: :oreder_details

  validates :genre_id, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :introduction, presence: true, length: { maximum: 300 }
  validates :price, presence: true


  #画像投稿機能
  attachment :image
  #販売ステータス
  enum is_active: {販売中:false,販売中止:true}

  #バリデーション の設定
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :public
  has_many :order_items, dependent: :destroy
  has_many :oreder_details, dependent: :destroy
  has_many :items, through: :oreder_details

  #validates :total_payment, presence: true, numericality: { greater_than: 0 }
  validates :shipping_cost, presence: true
  validates :payment_method, presence: true
  validates :status, presence: true
  validates :name, presence: true
  validates :postal_code, presence: true, length: { is: 7 }
  validates :address, presence: true
  validates :public_id, presence: true

  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }

   def self.total_amount_calculator(cart_items)
    sum = 0
    cart_items.each do |cart_item|
      sum += cart_item.amount * cart_item.item.price
    end
    sum * 1.1
  end


end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order

end

app/models/oreder_detail.rb
class OrederDetail < ApplicationRecord

  belongs_to :item
  belongs_to :order

  validates :making_status, presence: true
  validates :amount, presence: true
  validates :price, presence: true

  enum making_status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3 }

end

app/models/public.rb
class Public < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders
  has_many :addresses
  has_many :items, through: :cart_items

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :telephone_number, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  def name
    last_name + first_name
  end

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [

    :last_name,
    :first_name,
    :last_name_kana,
    :first_name_kana,
    :postal_code,
    :prefecture_name,
    :telephone_number,
    :address
  ])
 end

  def after_sign_out_path_for(resource)
    case resource
    when :admin
      new_admin_session_path
    when :public
      new_public_session_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all  #reverse_order(params[:page]).per(4) 引数エラーになります
    @items = Item.page(params[:page]).per(4)
  end

  def about
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_cart_item
    @order = Order.find(params[:id])
    @oreder_details = @oreder.oreder_details
  end

  # 小数点切り捨てはfloor,３桁区切りはto_s(:delimited)
  # 税込の計算
  def tax_price(price)
    (price * 1.1).floor
  end

  # 小計の計算
  def sub_price(sub)
    (tax_price(sub.item.price) * sub.amount)
  end

  # 合計金額の計算
  def total_payment(totals)
    price = 0
    totals.each do |total|
      price += sub_price(total)
    end
    price
  end



  def include_tax(price)
    tax = 1.1
    ((price * tax).round(2)).ceil
  end

  def registred_address(address)
    "〒" + address.postal_code + "  " + address.address + "  " + address.name
  end

  def subtotal(select_item)
    include_tax(select_item.item.price) * select_item.amount
  end

  def total(select_items)
    @total_payment = 0
    select_items.each do |select_item|
      @total_payment +=  subtotal(select_item)
    end
    return @total_payment
  end

  def order_total(select_items)
    @total_payment = 0
    select_items.each do |select_item|
      @total_payment += order_subtotal(select_item)
    end
    return @total_payment
  end

  def order_subtotal(select_item)
    select_item.item_price * select_item.amount
  end



end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/order_item_helper.rb
module OrderItemHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %> 
    <div class = "alert alert-warning">
        <ul>
            <% model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
    <div class="container">
      <a class="navbar-brand" href="/"><span>ながのCAKE</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if public_signed_in? %>
          <li class="text-light" style="margin-top:8px;">ようこそ、<%= current_public.last_name %>さん！</li>
          <li><%= link_to ' マイページ',public_customer_path(current_public),class: 'nav-link text-light' %></li>
          <li><%= link_to ' 商品一覧',public_items_path,class: 'nav-link text-light' %></li>
          <li><%= link_to ' カート',public_cart_items_path,class: 'nav-link text-light'%></li>
          <li><%= link_to ' ログアウト', destroy_public_session_path, method: :delete,class: 'nav-link text-light' %></li>
        <% elsif admin_signed_in? %>
          <li><%= link_to ' 商品一覧',admin_items_path,class: 'nav-link text-light' %></li>
          <li><%= link_to ' 会員一覧',admin_customers_path,class: 'nav-link text-light' %></li>
          <li><%= link_to ' 注文履歴一覧',admin_orders_path,class: 'nav-link text-light'%></li>
          <li><%= link_to ' ジャンル一覧',admin_genres_path,class: 'nav-link text-light'%></li>
          <li><%= link_to ' ログアウト', destroy_admin_session_path, method: :delete,class: 'nav-link text-light' %></li>
        <% else %>
          <li><%= link_to ' About',homes_about_path,class: 'nav-link text-light' %></li>
          <li><%= link_to ' 商品一覧',public_items_path,class: 'nav-link text-light' %></li>
          <li><%= link_to ' 新規登録', new_public_registration_path,class: 'nav-link text-light' %></li>
          <li><%= link_to ' ログイン', new_public_session_path ,class: 'nav-link text-light'%></li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <%= render 'layouts/header' %>
    <div class="container content">
       <%= yield %>
    </div>
    <div class="footer"></div>
  </body>
</html>